name: Percy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: npm ci
      - run: npm run build
      - run: npm run start-background

      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "cypress run"
        env:
          PERCY_TOKEN: ffe74745b12eb336803c09084b0e4c381c64523fafdf6f167291d4c980a40e94
